import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalNavbar from "./components/navigation/global_navbar";
import LocalNavbar from "./components/navigation/local_navbar";
import LearnMoreNavbar from "./components/navigation/learn_more_navbar";
import Footer from "./components/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalNavbar />
        <LocalNavbar />
        <LearnMoreNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
